# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_tourdates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tourdates',
            new_name='Tourdate',
        ),
    ]
