# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_tourdate_tourdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdate',
            name='tourcity',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourdate',
            name='tourinfourl',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourdate',
            name='tourvenue',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
